import os
import re
from pathlib import Path
from app.llm.client import call_llm, load_prompt

def generate_mom(transcript_text: str, nlp_summary: str = "") -> str:
    if not transcript_text or not transcript_text.strip():
        return "# Minutes of Meeting\n\nNo transcript content provided."

    combined_input = transcript_text
    if nlp_summary and nlp_summary.strip():
        combined_input = f"{transcript_text}\n\n[Additional Intelligence / NLP Context]:\n{nlp_summary}"

    try:
        prompt_content = load_prompt("mom.txt", transcript=combined_input)
    except Exception as e:
        print(f"[Warning] Could not load prompts/mom.txt: {e}")
        prompt_content = (
            "You are an executive secretary. Generate exhaustive, highly detailed Minutes of Meeting (MoM) in Markdown without any emojis. "
            "Cover Meeting Overview, Executive Summary, Detailed Agenda Items, Confirmed Decisions, and Action Items.\n\n"
            f"Transcript:\n{combined_input}\n\nMinutes of Meeting:"
        )

    try:
        return call_llm(prompt_content, temperature=0.2)
    except Exception as err:
        print(f"[MoM Generator Notice] LLM unavailable ({err}). Generating structured NLP MoM.")
        return generate_fallback_mom(transcript_text, nlp_summary)


def generate_fallback_mom(transcript_text: str, nlp_summary: str = "") -> str:
    """Generates a structured Minutes of Meeting when local LLM is offline."""
    lines = [line.strip() for line in transcript_text.split("\n") if line.strip()]
    first_few = " ".join(lines[:5]) if lines else "Meeting discussion recorded."
    
    actions = []
    action_keywords = ["will", "need to", "action", "review", "send", "prepare", "complete", "assign"]
    for line in lines:
        if any(kw in line.lower() for kw in action_keywords):
            actions.append(f"- {line}")
    if not actions:
        actions = ["- Review meeting discussion points and confirm next steps with team members."]

    return f"""# Minutes of Meeting (MoM)

## 1. Executive Summary
{first_few}

## 2. Key Discussion Topics & Highlights
{transcript_text[:1500]}...

## 3. Action Items & Decisions
{"\n".join(actions[:10])}

---
*Generated by MeetMemo NLP Engine.*
"""


def generate_mom_llm(transcript_text: str, *args, **kwargs) -> str:
    nlp_summary = args[0] if args else kwargs.get("nlp_summary", "")
    return generate_mom(transcript_text, nlp_summary=nlp_summary)